from yacs.config import CfgNode as CN

_C = CN()

_C.ACCELERATE = CN()
_C.ACCELERATE.PROJECT_NAME = "ISFM"
_C.ACCELERATE.RUN_NAME = "cross_fre"
_C.ACCELERATE.MIXED_PRECISION = "fp16"
_C.ACCELERATE.ALLOW_TF32 = True
_C.ACCELERATE.SEED = 3407
_C.ACCELERATE.GRADIENT_ACCUMULATION_STEPS = 1
_C.ACCELERATE.LOG_PERIOD = 50
_C.ACCELERATE.EVAL_PERIOD = 10

_C.MODEL = CN()
_C.MODEL.PRETRAINED_PATH = ""
_C.MODEL.LAST_EPOCH = 0

_C.MODEL.MAMBA_CONFIG = CN()
_C.MODEL.MAMBA_CONFIG.DEPTHS = [2, 2, 2, 2]
_C.MODEL.MAMBA_CONFIG.EMBED_DIM = 512
_C.MODEL.MAMBA_CONFIG.IMG_SIZE = 32
_C.MODEL.MAMBA_CONFIG.MLP_RATIO = 2.0

_C.MODEL.SWIN_BLOCK_CONFIG = CN()
_C.MODEL.SWIN_BLOCK_CONFIG.PRETRAINED_PATH = "pretrained_models/swin/swin_base_patch4_window12_384_22kto1k.pth"
_C.MODEL.SWIN_BLOCK_CONFIG.EMBED_DIM = 512
_C.MODEL.SWIN_BLOCK_CONFIG.INNER_DIM = 16
_C.MODEL.SWIN_BLOCK_CONFIG.DEPTHS = [2, 2, 18, 2]
_C.MODEL.SWIN_BLOCK_CONFIG.NUM_HEADS = [4, 8, 16, 32]
_C.MODEL.SWIN_BLOCK_CONFIG.WINDOW_SIZE = 16
_C.MODEL.SWIN_BLOCK_CONFIG.DROP_PATH_RATE = 0.2
_C.MODEL.SWIN_BLOCK_CONFIG.LAST_NORM = False
_C.MODEL.SWIN_BLOCK_CONFIG.GUIDANCE_DIM = 81
_C.MODEL.SWIN_BLOCK_CONFIG.IMG_SIZE = 32

_C.OPTIMIZER = CN()
_C.OPTIMIZER.NAME = "adam"
_C.OPTIMIZER.EPOCHS = 100
_C.OPTIMIZER.WARMUP_STEPS = 1000
_C.OPTIMIZER.DECAY_EPOCHS = [50]
_C.OPTIMIZER.LR = 1.0e-4
_C.OPTIMIZER.SCALE_LR = False
_C.OPTIMIZER.WARMUP_RATE = 0.1
_C.OPTIMIZER.WARMUP_ITER = 5
_C.OPTIMIZER.DECAY_RATE = 0.1
_C.OPTIMIZER.WEIGHT_DECAY = 0.05
_C.OPTIMIZER.OVERRIDE_LR = 0.
_C.OPTIMIZER.SCHEDULER = 'linear'

_C.INPUT = CN()
_C.INPUT.IMG_SIZE = [256, 256]
_C.INPUT.ROOT_DIR = ""
_C.INPUT.VIF_DIR = ""
_C.INPUT.MFF_DIR = ""
_C.INPUT.MEF_DIR = ""
_C.INPUT.MIF_DIR = ""
_C.INPUT.BATCH_SIZE = 4
_C.INPUT.NUM_WORKERS = 8
_C.INPUT.TASK_CONFIG = [""]

_C.TEST = CN()
_C.TEST.MICRO_BATCH_SIZE = 1
_C.TEST.NUM_WORKERS = 8
_C.TEST.CHECKPOINT_PATH = ""
_C.TEST.IMG_SIZE = [256, 256]
_C.TEST.TASK_CONFIG = [""]
_C.TEST.VIF_DIR = ""
_C.TEST.MFF_DIR = ""
_C.TEST.MEF_DIR = ""
_C.TEST.MIF_DIR = ""

